### ISSUE TITLE
*P2* - "Change navbar links"

### ISSUE THREAD

**Issue by ManuelP02** [Mtduffey36/hair-and-co#68]
Acceptance Criteria:

GIVEN "All kind of user sign-in into their accounts"
THEN "We need to show different things on the navbar EX: swap sign in for sign out, depending on user role links can vary"

**Comment by Ejacosta86** [comment]
navbar on landing page shows correctly however still having issues showing the admin navbar without refreshing the page.

**Comment by AndresAlbornozgil** [comment]
done

**Comment by Mtduffey36** [comment]
"navbar on landing page shows correctly however still having issues showing the admin navbar without refreshing the page."

still happening
